theme: jekyll-theme-minimal
#remote_theme: andreondra/jekyll-theme-simplex
title: [bioinformatica miscellanea]
description: [Short bioinformatics tutorials for the microbially-inclined <\b> non-comprehensive and pseudo-random]
logo: aylward_logo.png
