#theme: jekyll-theme-cayman
remote_theme: amitmerchant1990/reverie
title: [bioinformatica miscellanea]
description: [Short bioinformatics tutorials for the microbially-inclined]
logo: aylward_logo.png
