theme: jekyll-theme-minimal
title: [Aylward lab bioinformatics tutorials]
description: [Short tutorials for introductory bioinformatics]
logo: ["https://github.com/faylward/bioinformatics_tutorials/blob/master/aylward_logo.png"]
