theme: jekyll-theme-minimal
#remote_theme: andreondra/jekyll-theme-simplex
title: [bioinformatica miscellanea]
description: [Short bioinformatics tutorials for the microbially inclined - non-comprehensive - pseudo-random]
