theme: jekyll-theme-minimal
#remote_theme: andreondra/jekyll-theme-simplex
title: [Introduction to the command line]
description: [Short bioinformatics tutorials for the microbially inclined - non-comprehensive - pseudo-random]
